[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0" 